server:
  tomcat:
    additional-tld-skip-patterns: "*.jar"    # 구동시 Failed to scan orai18n-mapping.jar from classloader hierarchy 경고 문제로 인해 톰캣의 scan skip
   
# 동기화 작업 thread 수..추후 확장을 위해 추가함      
sync:
  thread: 1
              
---
spring:  
  batch:
    chunk-size: 10000
    sleep-time: 5000    
    job:      
      names: ${job.name:NONE} # 시작 job 받아옴
  profiles:
    include:
    - common-jdbc
    - common-msa 
 